#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#################################################################################
# Copyright (c) 2010 Dimitri Merejkowsky                                        #
#                                                                               #
# Permission is hereby granted, free of charge, to any person obtaining a copy  #
# of this software and associated documentation files (the "Software"), to deal #
# in the Software without restriction, including without limitation the rights  #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell     #
# copies of the Software, and to permit persons to whom the Software is         #
# furnished to do so, subject to the following conditions:                      #
#                                                                               #
# The above copyright notice and this permission notice shall be included in    #
# all copies or substantial portions of the Software.                           #
#                                                                               #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,      #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE   #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER        #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN     #
# THE SOFTWARE.                                                                 #
#################################################################################


"""
Quick rewrite of podget in python
Required: feeparser
Optional:  pogressbar

You must edit the ~/.condfig/pypodget/pypodget.conf
file before using this software

Usage: pypodget [--verbose]
    --verbose option requires python-progressbar

"""


from urllib.request import urlopen
import os
import sys
import time

from configparser import SafeConfigParser

HAS_PROGRESSBAR = True

try:
    import feedparser
except ImportError:
    print("Error, could not find feedparser module")
    sys.exit(1)

try:
    from progressbar import ProgressBar
    from progressbar import Percentage
    from progressbar import FileTransferSpeed
    from progressbar import ETA
    from progressbar import Bar
except ImportError:
    HAS_PROGRESSBAR = False


class PodcastDownloader:
    """
    Initialized with a nickname and a url.

    Retrieve the rss file from the URL, and for each entry in the feed,
    download it, then save file in
    OUTPUT/nickname/date.mp3

    """
    OUTPUT = ""

    def __init__(self, url, nick_name, verbose=False):
        self.url       = url
        self.nick_name = nick_name
        self.entries   = []
        self.verbose   = verbose


    def download(self):
        """
        Main method.

        """
        self.retrieve_info()
        self.retrieve_content()


    def retrieve_info(self):
        """
        Retrieve the XML Rss file, and updates the self.entries
        list.

        """
        feed = feedparser.parse(self.url)
        self.entries = feed.entries


    def retrieve_content(self):
        """
        Now that we got the information, get the files and save them.

        """
        for entry in self.entries:
            output_path = os.path.join(PodcastDownloader.OUTPUT, self.nick_name)
            url  = entry.id
            date = entry.updated_parsed

            # Get filename extension from URL:
            file_extension = url.split(".")[-1]
            date_str  = time.strftime("%Y-%m-%d", date)
            file_name = date_str + "." + file_extension
            file_path = os.path.join(output_path, file_name)

            if not os.path.exists(output_path):
                os.makedirs(output_path)

            if os.path.exists(file_path):
                if self.verbose:
                    print(file_path, "already exists, skipping")
                continue

            if self.verbose:
                print("Downloading ", url)
                print("Saving to", file_path)
            try:
                source = urlopen(url)
            except IOError as err:
                mess  = "Failed to download %s \n" % url
                mess += "Error was %s \n"          % err
                sys.stderr.write(mess)
                continue

            size = int(source.headers.get("content-length"))
            buf_size = 16 * 1024 # (same length as in shtutil.copyfileobj)
            if self.verbose:
                pbar = ProgressBar(
                  widgets = [
                    Percentage()                          ,
                    " "                                   ,
                    Bar(marker='#', left='[', right=']' ) ,
                    " - "                                 ,
                    FileTransferSpeed()                   ,
                    " | "                                 ,
                    ETA() ]                               ,
                  maxval = size )
                pbar.start()

            output = open(file_path, "wb")
            done    = 0
            content = source.read(buf_size)

            while content:
                done += buf_size
                if done > size:
                    done = size

                if self.verbose:
                    pbar.update(done)

                output.write(content)
                content = source.read(buf_size)

            output.close()



def _get_config():
    """
    Read .config/pypodget/.

    Returns a list of tuples (<urls>, <nicknames>)

    Also, set OUTPUT static member of PodcastDownloader
    class

    """
    res = []
    config_path = os.path.expanduser("~/.config/pypodget/pypodget.conf")
    conf_header = """# Pypodget configuration file

# Puts global options in the [core] section
"""
    conf_footer = """# Add your podcasts this way:
# [Name]
# url = http://example.com/feed.xml
"""
    config_parser = SafeConfigParser()
    if not os.path.exists(config_path):
        # Let's create an empty config file,
        # and the necessary dirs if needed
        base_path = os.path.dirname(config_path)
        if not os.path.exists(base_path):
            os.makedirs(base_path)

        config_parser.add_section("core")
        config_parser.set("core", "output", "~/Podcasts")
        try:
            config_file = open(config_path, "w")
        except IOError:
            print("Warning, could not open", config_path, "for writing")
        config_file.write(conf_header)
        config_parser.write(config_file)
        config_file.write(conf_footer)
        config_file.close()

    config_parser.readfp(open(config_path, "r"))
    output = config_parser.get("core", "output")
    output = os.path.expanduser(output)
    PodcastDownloader.OUTPUT = output

    feeds = [x for x in config_parser.sections() if x != "core"]
    for feed in feeds:
        res.append((config_parser.get(feed, "url"), feed))

    return res


def main():
    """
    Manages options when called from command-line
    """
    feeds = _get_config()
    verbose = False
    if len(sys.argv) > 1:
        if "--verbose" in sys.argv[1]:
            if not HAS_PROGRESSBAR:
                print("--verbose needs python-progressbar")
                exit(2)
            verbose = True

    for (url, nick_name) in feeds:
        podcast_downloader = PodcastDownloader(url, nick_name, verbose)
        podcast_downloader.download()


if __name__ == "__main__" :
    main()

